server:
  port: 80

spring:
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.129.20:3306/project?useUnicode=true&characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000&tinyInt1isBit=false&serverTimezone=GMT%2B8
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 192.168.129.20
    port: 6379
    password:
    #连接redis超时时间（毫秒）
    timeout: 0ms
    jedis:
      pool:
        #最大等待时间
        max-wait: 1000ms
        #最小空闲数量
        min-idle: 1
        #最大空闲数量
        max-idle: 10
        #最大连接数量
        max-active: 1000


